src/config/routes.rb
  post "sync_schedules/apply"

  get "sync_management/manage"
  get "sync_management/index"
  post "sync_management/sync"
  get  "sync_management/sync_status"
  get  "sync_management/product_status"
  resources :sync_management, :only => [:destroy]

  get "notices/note_count"
  get "notices/get_new"
  get "notices/auto_complete_search"
  match 'notices/:id/details' => 'notices#details', :via => :get, :as => 'notices_details'
  match 'notices' => 'notices#show', :via => :get
  match 'notices' => 'notices#destroy_all', :via => :delete

  resources :subscriptions do
    member do
      get :edit
      get :products
      get :consumers
    end
    collection do
      get :items
      post :upload
      post :delete_manifest
      get :history
      get :history_items
    end
  end

  resources :dashboard, :only => [:index] do
    collection do
      get :sync
      get :notices
      get :errata
      get :promotions
      get :systems
      get :system_groups
      get :subscriptions
    end
  end

  resources :systems do
    resources :events, :only => [:index, :show], :controller => "system_events" do
      collection do
        get :status
        get :more_events
        get :items
      end
    end
    resources :system_packages, :only => {} do
      collection do
        put :add
        post :remove
        post :update
        get :packages
        get :more_packages
        get :status
      end
    end
    resources :errata, :controller => "system_errata", :only => [:index, :update] do
      collection do
        get :items
        post :install
        get :status
      end
    end

    member do
      get :edit
      get :subscriptions
      post :update_subscriptions
      get :products
      get :more_products
      get :facts
      get :system_groups
      put :add_system_groups
      put :remove_system_groups
      get :custom_info
    end
    collection do
      get :auto_complete
      get :items
      get :env_items
      get :environments
      delete :bulk_destroy
      post :bulk_add_system_group
      post :bulk_remove_system_group
      post :bulk_content_install
      post :bulk_content_update
      post :bulk_content_remove
      post :bulk_errata_install
    end
  end
  resources :operations, :only => [:index]  do
  end

  resources :packages, :only => [:show] do
    member do
      get :changelog
      get :filelist
      get :dependencies
    end
    collection do
      get :auto_complete_library
      get :auto_complete_nvrea_library
      get :validate_name_library
    end
  end

  resources :errata, :only => [:show] do
    member do
      get :packages
      get :short_details
    end
  end

  resources :distributors do
    resources :events, :only => [:index, :show], :controller => "distributor_events" do
      collection do
        get :status
        get :more_events
        get :items
      end
    end

    member do
      get :edit
      get :subscriptions
      post :update_subscriptions
      get :products
      get :more_products
      get :download
    end
    collection do
      get :auto_complete
      get :items
      get :env_items
      get :environments
      delete :bulk_destroy
    end
  end

  resources :products, :only => [:new, :create, :edit,:update, :destroy] do
    collection do
       get :auto_complete
    end
  end

  resources :users do
    collection do
      get :auto_complete_search
      get :items
      post :enable_helptip
      post :disable_helptip
    end
    member do
      post :clear_helptips
      put :update_roles
      put :update_locale
      put :update_preference
      put :setup_default_org
      get :edit_environment
      put :update_environment
    end
  end

  resources :system_templates do
    collection do
      get :auto_complete_search
      get :items
      get :product_packages
      get :product_comps
      get :product_repos
    end
    member do
      get :promotion_details
      get :object
      get :download
      get :validate
      put :update_content
    end
  end

  resources :providers do
    collection do
      get :auto_complete_search
      put :refresh_products
    end

    resources :products do
      get :default_label, :on => :collection

      resources :repositories, :only => [:new, :create, :edit, :destroy] do
        get :default_label, :on => :collection
        member do
          put :update_gpg_key, :as => :update_repo_gpg_key
        end
      end
    end
    collection do
      get :items
      get :redhat_provider
      post :redhat_provider, :action => :update_redhat_provider
    end
    member do
      get :repo_discovery
      get :discovered_repos
      get :new_discovered_repos
      post :discover
      post :cancel_discovery
      get :products_repos
      get :manifest_progress
      get :schedule
    end
  end
  match '/providers/:id' => 'providers#update', :via => :put
  match '/providers/:id' => 'providers#update', :via => :post

  match '/repositories/:id/enable_repo' => 'repositories#enable_repo', :via => :put, :as => :enable_repo

  resources :repositories, :only => [:new, :create, :edit, :destroy] do
    get :auto_complete_library, :on => :collection

    resources :distributions, :only => [:show], :constraints => { :id => /[0-9a-zA-Z\-\+%_.]+/ } do
      member do
        get :filelist
      end
    end
  end

  resources :promotions, :only =>[] do
    collection do
      get :index, :action =>:show
    end
    member do
      get :show
      get :products
      get :packages
      get :errata
      get :system_templates
      get :repos
      get :distributions
      get :details
      get :content_views
    end

  end

  match '/organizations/:org_id/environments/:env_id/edit' => 'environments#update', :via => :put

  resources :organizations do
    collection do
      get :auto_complete_search
      get :items
      get :default_label
    end
    member do
      get :environments_partial
      get :events
      get :download_debug_certificate
    end
    resources :environments do
      get :default_label, :on => :collection
      member do
        get :system_templates
        get :products
        get :content_views
      end
      resources :content_view_versions, :only => [:show] do
        member do
          get :content
        end
      end
    end
  end
  match '/organizations/:id/edit' => 'organizations#update', :via => :put

  resources :changesets, :only => [:update, :index, :show, :create, :new, :edit, :destroy] do
    member do
      put :name
      get :dependencies
      post :apply
      get :status
      get :object
    end
    collection do
      get :auto_complete_search
      get :list
      get :items
    end
  end

  resources :environments

  match '/roles/show_permission' => 'roles#show_permission', :via=>:get
  resources :roles do
    put "create_permission" => "roles#create_permission"

    resources :permission, :only => {} do
      delete "destroy_permission" => "roles#destroy_permission", :as => "destroy"
      post "update_permission" => "roles#update_permission", :as => "update"
    end
    collection do
      get :auto_complete_search
      get :items
    end
    resources :ldap_groups, :only => [] do
      member do
		delete "destroy" => "roles#destroy_ldap_group", :as => "destroy"
      end
      collection do
		post "create" => "roles#create_ldap_group", :as => "create"
      end
    end
  end
  match '/roles/:organization_id/resource_type/verbs_and_scopes' => 'roles#verbs_and_scopes', :via=>:get, :as=>'verbs_and_scopes'

  resources :search, :only => {} do
    get 'show', :on => :collection

    get 'history', :on => :collection
    delete 'history' => 'search#destroy_history', :on => :collection

    get 'favorite', :on => :collection
    post 'favorite' => 'search#create_favorite', :on => :collection
    delete 'favorite/:id' => 'search#destroy_favorite', :on => :collection, :as => 'destroy_favorite'
  end

  resource :user_session do
    post 'set_org'
    get 'allowed_orgs'
  end


  root :to => "user_sessions#new"

  match '/login' => 'user_sessions#new', :as=>'login'
  match '/logout' => 'user_sessions#destroy', :via=>:post
  match '/user_session/logout' => 'user_sessions#destroy'
  match '/user_session' => 'user_sessions#show', :via=>:get, :as=>'show_user_session'

  resources :password_resets, :only => [:create, :edit, :update] do
    collection do
      post :email_logins
    end
  end

  # custom information
  match '/custom_info/:informable_type/:informable_id' => 'custom_info#create', :via => :post, :as => :create_custom_info
  match '/custom_info/:informable_type/:informable_id' => 'custom_info#index', :via => :get, :as => :custom_info
  match '/custom_info/:informable_type/:informable_id/:keyname' => 'custom_info#show', :via => :get, :as => :show_custom_info
  match '/custom_info/:informable_type/:informable_id/:keyname' => 'custom_info#update', :via => :put, :as => :update_custom_info
  match '/custom_info/:informable_type/:informable_id/:keyname' => 'custom_info#destroy', :via => :delete, :as => :destroy_custom_info

  namespace :api do
    class RegisterWithActivationKeyContraint
      def matches?(request)
        request.params[:activation_keys]
      end
    end
    match '/' => 'root#resource_list'

    # Headpin does not support system creation
    if Katello.config.katello?
      onlies = [:show, :destroy, :create, :index, :update]
    else
      onlies = [:show, :destroy, :index, :update]
    end
    resources :systems, :only => onlies do
      member do
        get :packages, :action => :package_profile
        get :errata
        get :pools
        get :releases
        put :enabled_repos
        post :system_groups, :action => :add_system_groups
        delete :system_groups, :action => :remove_system_groups
      end
      collection do
        match "/tasks/:id" => "systems#task_show", :via => :get
      end
      resources :subscriptions, :only => [:create, :index, :destroy] do
        collection do

src/app/models/authorization/user.rb
#
# Copyright 2011 Red Hat, Inc.
#
# This software is licensed to you under the GNU General Public
# License as published by the Free Software Foundation; either version
# 2 of the License (GPLv2) or (at your option) any later version.
# There is NO WARRANTY for this software, express or implied,
# including the implied warranties of MERCHANTABILITY,
# NON-INFRINGEMENT, or FITNESS FOR A PARTICULAR PURPOSE. You should
# have received a copy of GPLv2 along with this software; if not, see
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.



module Authorization::User
  extend ActiveSupport::Concern

  READ_PERM_VERBS = [:read, :update, :create, :delete]

  included do
    scope :readable, lambda { User.allowed_all_tags?(READ_PERM_VERBS, :users) ?
        where(:hidden => false) : where("0 = 1") }
  end


  module ClassMethods
    def creatable?
      User.allowed_to?([:create], :users, nil)
    end

    def any_readable?
      User.allowed_to?(READ_PERM_VERBS, :users, nil)
    end

    def list_verbs(global=false)
      { :create => _("Administer Users"),
        :read   => _("Read Users"),
        :update => _("Modify Users"),
        :delete => _("Delete Users")
      }.with_indifferent_access
    end

    def read_verbs
      [:read]
    end

    def no_tag_verbs
      [:create]
    end
  end


  module InstanceMethods
    def readable?
      User.any_readable? && !hidden
    end

    def editable?
      User.allowed_to?([:create, :update], :users, nil) && !hidden
    end

    def deletable?
      self.id != User.current.id && User.allowed_to?([:delete], :users, nil)
    end

    def allowed_organizations
      #test for all orgs
      perms = ::Permission.joins(:role).joins("INNER JOIN roles_users ON roles_users.role_id = roles.id").
          where("roles_users.user_id = ?", self.id).where(:organization_id => nil).count()
      return ::Organization.all if perms > 0

      perms = ::Permission.joins(:role).joins("INNER JOIN roles_users ON roles_users.role_id = roles.id").
          where("roles_users.user_id = ?", self.id).where("organization_id is NOT null")
      #return the individual organizations
      perms.collect { |perm| perm.organization }.uniq
    end
  end

end

src/app/models/foreman/user.rb
#
# Copyright 2012 Red Hat, Inc.
#
# This software is licensed to you under the GNU General Public
# License as published by the Free Software Foundation; either version
# 2 of the License (GPLv2) or (at your option) any later version.
# There is NO WARRANTY for this software, express or implied,
# including the implied warranties of MERCHANTABILITY,
# NON-INFRINGEMENT, or FITNESS FOR A PARTICULAR PURPOSE. You should
# have received a copy of GPLv2 along with this software; if not, see
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.

module Foreman
  class User < Resources::ForemanModel

    attributes :login, :mail, :admin, :password

    def json_default_options
      { :only => [:login, :mail, :admin] }
    end

    def json_create_options
      { :only    => [:login, :mail, :admin, :password],
        :methods => [:auth_source_id] }
    end

    def json_update_options
      { :only    => [:mail, :password] }
    end

    def auth_source_id
      1
    end

  end
end

src/app/models/glue/elastic_search/user.rb
#
# Copyright 2011 Red Hat, Inc.
#
# This software is licensed to you under the GNU General Public
# License as published by the Free Software Foundation; either version
# 2 of the License (GPLv2) or (at your option) any later version.
# There is NO WARRANTY for this software, express or implied,
# including the implied warranties of MERCHANTABILITY,
# NON-INFRINGEMENT, or FITNESS FOR A PARTICULAR PURPOSE. You should
# have received a copy of GPLv2 along with this software; if not, see
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.


module Glue::ElasticSearch::User
  def self.included(base)
    base.send :include, Ext::IndexedModel

    base.class_eval do
      index_options :extended_json => :extended_index_attrs,
                    :display_attrs => [:username, :email],
                    :json          => { :except => [:password, :password_reset_token,
                                                    :password_reset_sent_at, :helptips_enabled,
                                                    :disabled, :login] }

      mapping do
        indexes :username, :type => 'string', :analyzer => :kt_name_analyzer
        indexes :username_sort, :type => 'string', :index => :not_analyzed
      end
    end
  end

  def extended_index_attrs
    { :username_sort => username.downcase }
  end


end

src/app/helpers/users_helper.rb
#
# Copyright 2011 Red Hat, Inc.
#
# This software is licensed to you under the GNU General Public
# License as published by the Free Software Foundation; either version
# 2 of the License (GPLv2) or (at your option) any later version.
# There is NO WARRANTY for this software, express or implied,
# including the implied warranties of MERCHANTABILITY,
# NON-INFRINGEMENT, or FITNESS FOR A PARTICULAR PURPOSE. You should
# have received a copy of GPLv2 along with this software; if not, see
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.

module UsersHelper

  def mask_password user
    return "" if user.password.nil?
    user.password.gsub(/./, "&#9679;")
  end

  def organization_select(org_id=nil, optional=true)
    if current_user.id == @user.id
      orgs = current_user.allowed_organizations.reject do |org|
        !org.any_systems_registerable?
      end
    else
      orgs = Organization.without_deleting.all
    end
    choices = orgs.map {|a| [a.name, a.id]}
    if optional
      selected = org_id
      prompt = nil
      choices.unshift [_('Select Organization'), nil]
    else
      selected = org_id || current_organization.id
      prompt = _('Select Organization')
    end
    select(:org_id, "org_id", choices, {:prompt => prompt, :id=>"org_field", :selected => selected}, {:class=>"one-line-ellipsis", :style=>"width: 300px; max-width: 300px"})
  end

  def locale_select(locale=nil)
    choices = [_('Use Browser Locale')].concat(Katello.config.available_locales)
    selected =  (locale == nil) ? _('Use Browser Locale') : locale
    select(:locale, "locale", choices,
           {:prompt => nil, :id=>"locale_field",
           :selected => selected})
  end
end

src/app/views/users/_edit.html.haml
= content_for :title do
  #{@user.username}
  
= content_for :remove_item do
  -if @user.deletable?
    = link_to _("Remove User"), { :controller => "users", :action => "destroy" }, :confirm => _('Are you sure you want to remove this user?'), :method => :delete, :class=>"remove_item", :remote=>true
  
= content_for :navigation do
  = render_menu(1..2, user_navigation)

= content_for :content do
  = render :partial => "edit_form", :locals=>{:editable=>editable, :accessible_envs => accessible_envs, :ldap => ldap}

= render :template => "layouts/tupane_layout"

src/app/views/users/_edit_environment.html.haml
= javascript do
  :plain
    localize({
      "noDefaultEnv": '#{escape_javascript(_("No default environment. Select an organization to choose from available environments."))}'
    });
    env_select.original_env_id = '#{@old_env ? @old_env.id : ''}';
    env_select.ajax_params = {};
    env_select.ajax_params["user_id"] = '#{@user.id}';

= content_for :title do
  #{@user.username}

= content_for :remove_item do
  -if @user.deletable?
    = link_to _("Remove User"), { :controller => "users", :action => "destroy" }, :confirm => _('Are you sure you want to remove this user?'), :method => :delete, :class=>"remove_item", :remote=>true

= content_for :navigation do
  = render_menu(1..2, user_navigation)

= content_for :content do
  %fieldset.fl.clear
    %h5
      #{_("Current System Registration Defaults")}
    .grid_2.ra
      = label :user, :org, _("Organization:")
    .grid_7.la#org_name
      = @old_env ? @old_env.organization.name : _("No system registration default set for this user.")
    .grid_2.ra.clear
      = label :user, :env, _("Environment:")
    .grid_7.la#env_name
      = @old_env ? @old_env.name : _("No system registration default set for this user.")
  - if editable
    %fieldset.fl.clear
      %h5
        #{_("Choose New System Registration Defaults:")}
    %fieldset.fl.clear
      .grid_2.ra
        = label :user, :org, _("Organization:")
      .grid_7.la
        = organization_select (@organization ? @organization.id : nil)
    %fieldset.fl.clear
    .promotion_paths
      = hidden_field_tag 'user[environment_id]', @environment.id unless @environment.nil?
      .grid_2.ra
        %label #{_("Environment")}:
      .grid_7.la
        = image_tag( "embed/icons/spinner.gif", :id=>"org_spinner", :class=>"hidden fl")
        - if @environment.nil?
          #env_box
            -if @organization.nil?
              #{_("No system registration default environment. Select an organization to choose from available environments.")}
            -else
              #{_("No environments are currently available in this organization. Saving will set user to no system registration default environment.")}
        - else
          #env_box
            = environment_selector(:path_widget_class=>"grid_5", :path_entries_class=>"grid_5", :library_clickable=>false,
              :accessible_envs=>accessible_envs)
      .clear
        &nbsp;
      .grid_5.la.prefix_2
        #update_user.verify_password.disabled.button{'data-url'=>update_environment_user_path(@user.id)}
          #{_("Save")}

= render :template => "layouts/tupane_layout"

src/app/views/users/_edit_form.html.haml
= javascript do
  :plain
    //what button should be disabled when passwords don't match

    localize({
      "password_match": '#{escape_javascript(_('The passwords do not match'))}',
      "very_weak": '#{escape_javascript(_("Very Weak"))}',
      "weak": '#{escape_javascript(_("Weak"))}',
      "good": '#{escape_javascript(_("Good"))}',
      "strong": '#{escape_javascript(_("Strong"))}',
      "meterText": '#{escape_javascript(_("Password Strength"))}',
      "usernameMatch": '#{escape_javascript(_("The password should not contain the username."))}'
    });

= javascript :edit_helpers

#users
  .grid_10

    %fieldset
      .grid_3.ra
        = label :user, :name, _("Username:")
      #username.grid_5.la
        #{@user.username}

    %fieldset
      .grid_3.ra
        = label :user, :helptips_enable, _("Inline Help Enabled:")
      .grid_5.la
        - if editable
          = check_box("user", "helptips_enabled", :id=>"helptips_enabled", 'data-url'=>user_path(@user.id), :checked=>@user.helptips_enabled ? "checked": "")
        - else
          = @user.helptips_enabled ? _("Yes") : _("No")

    - if editable
      %fieldset.fl.clear
        .grid_3.ra
          = label :user, :username, _("Clear Disabled Helptips:")
        .grid_5.la
          #clear_helptips{:class=>"button", "data-url"=>clear_helptips_user_path(@user.id)}
            = _("Clear")

      - if !ldap
        %fieldset.fl.clear
          .grid_3.ra
            = label :user, :password, _("Change Password:")
          .grid_5.la
            = text_field :user, :password, :id=>"password_field", :value=>"", :type=>"password"

        %fieldset.fl.clear
          .grid_3.ra
            = label :user, :username, _("Confirm:")
          .grid_5.la
            = text_field :user, :username, :id=>"confirm_field", :value=>"", :type=>"password"
        %fieldset.fl.clear
          .grid_5.la.prefix_2
            #password_conflict
          .grid_5.la.prefix_3
            #save_password.verify_password.disabled.button{'data-url'=>user_path(@user.id)}
              #{_('Save')}

  - if !ldap
    .grid_10
      = form_tag user_path(@user), :method => :put, :remote => true do
        %fieldset
          .grid_3.ra
            = label :user, :email, _("Email Address:")
          .grid_5.la{'name' => 'user[email]',  :class => editable_class(editable), 'data-url' => user_path(@user)} #{@user.email}

  .grid_10
    = form_tag update_locale_user_path(@user), :id => "locale_form", :method => :put, :remote => false do
      %fieldset
        .grid_3.ra
          = label :user, :locale, "%s:" % _("Preferred Locale")
        - if editable
          .grid_5.la
            = locale_select @user.default_locale
        - else
          .grid_5.la
            =  @user.default_locale  || "#{_('Browser Default Locale')}"

src/app/views/users/_new.html.haml
= javascript do
  :plain
    localize({
      "noDefaultEnv": '#{escape_javascript(_("No default environment. Select an organization to choose from available environments."))}',
      "password_match": '#{escape_javascript(_('The passwords do not match'))}',
    });
    env_select.original_env_id = '';
    env_select.ajax_params={};
    env_select.ajax_params["new"]=true;

= content_for :title do
  #{_("New User")}

= content_for :navigation do
  / pretty

= content_for :content do
  .grid_10
    = kt_form_for User.new, :id => "new_user" do |form|

      = form.text_field :username, :label => _("Username:")

      - if !@ldap
        = form.text_field :email, :label => _("Email Address:"), :type => :email
        = form.text_field :password, :label => _("Password:"), :type => :password, :id => :password_field
        = form.text_field :password, :label => _("Confirm:"), :type => :password, :id => :confirm_field
        .grid_7.la.prefix_2
          #password_conflict

      %h5
        #{_("System Registration Defaults")}
      = form.field :org, :label => _("Organization:") do
        = organization_select

      .promotion_paths
        = hidden_field_tag 'user[environment_id]', @environment.id unless @environment.nil?
        = form.field :environment, :label => _("Environment:") do
          = image_tag( "embed/icons/spinner.gif", :id=>"org_spinner", :class=>"hidden fl")
          - if @environment.nil?
            #env_box
              -if @organization.nil?
                #{_("No default environment. Select an organization to choose from available environments.")}
              -else
                = no_env_available_msg
          - else
            #env_box
              = render "environments", :accessible_envs => accessible_envs

      = form.submit _("Save User"), :id => :save_user

= render :template => "layouts/tupane_layout"

src/app/views/users/index.html.haml
.grid_16#main
  = two_panel(@users, @panel_options)

= javascript :user, :multiselect, :edit_helpers

= javascript do
  :plain
    var current_username = '#{_(user.username)}';

src/app/views/users/show.html.haml
= javascript :multiselect, :user
/this page is used on the Roles users pane
= collection_select(:user, :roles, Role.all, :id, :name, {}, {:multiple=>:multiple, :class=>"multiselect", :style=>"width:500px; height:400px"})