src/config/routes.rb
Src::Application.routes.draw do

  apipie

  if Katello.config.use_foreman
    scope :module => 'foreman' do
      resources :subnets do
        collection do
          get :items
        end
      end

      resources :domains do
        collection do
          get :items
        end
      end

      resources :hardware_models do
        collection do
          get :items
        end
      end

      resources :architectures do
        collection do
          get :items
        end
      end

      resources :smart_proxies do
        collection do
          get :items
        end
      end
    end
  end

  resources :system_groups do
    collection do
      get :items
      get :auto_complete
      get :validate_name
    end
    member do
      post :copy
      get :systems
      post :add_systems
      post :remove_systems
      delete :destroy_systems
    end
    resources :events, :controller => "system_group_events", :only => [:index, :show] do
      collection do
        get :status
        get :more_items
        get :items
      end
    end
    resources :packages, :controller => "system_group_packages", :only => [:index] do
      collection do
        put :add
        put :remove
        put :update
        get :status
      end
    end
    resources :errata, :controller => "system_group_errata", :only => [:index] do
      collection do
        get :items
        post :install
        get :status
      end
    end
  end

  resources :content_search do
      collection do
        post :errata
        post :products
        post :packages
        post :packages_items
        post :errata_items
        post :repos
        post :views
        get :repo_packages
        get :repo_errata
        get :repo_compare_packages
        get :repo_compare_errata
      end
  end

  resources :content_view_definitions do
    collection do
      get :default_label
      get :items
    end
    member do
      post :clone
      get :views
      get :publish_setup
      post :publish
      get :status
      get :content
      post :update_content
      put :update_component_views
      get :filter
    end
    resources :content_view, :only => [], :controller => :content_view_definitions do
      member do
        post :refresh
      end
    end
  end

  resources :content_views do
    collection do
       get :auto_complete
    end
  end

  resources :activation_keys do
    collection do
      get :auto_complete_search
      get :items
      get :subscriptions
    end
    member do
      get :applied_subscriptions
      get :available_subscriptions
      post :remove_subscriptions
      post :add_subscriptions

      post :update

      get :system_groups
      get :systems
      put :add_system_groups
      put :remove_system_groups
    end
  end

  resources :gpg_keys do
    collection do
      get :auto_complete_search
      get :items
    end
    member do
      get :products_repos
      post :update
    end
  end

  resources :sync_plans, :only => [:index, :create, :new, :edit, :update, :show, :destroy, :auto_complete_search] do
    collection do
      get :auto_complete_search
      get :items
    end
  end

  get  "sync_schedules/index"
  post "sync_schedules/apply"

  get "sync_management/manage"
  get "sync_management/index"
  post "sync_management/sync"
  get  "sync_management/sync_status"
  get  "sync_management/product_status"
  resources :sync_management, :only => [:destroy]

  get "notices/note_count"
  get "notices/get_new"
  get "notices/auto_complete_search"
  match 'notices/:id/details' => 'notices#details', :via => :get, :as => 'notices_details'
  match 'notices' => 'notices#show', :via => :get
  match 'notices' => 'notices#destroy_all', :via => :delete

  resources :subscriptions do
    member do
      get :edit
      get :products
      get :consumers
    end
    collection do
      get :items
      post :upload
      post :delete_manifest
      get :history
      get :history_items
    end
  end

  resources :dashboard, :only => [:index] do
    collection do
      get :sync
      get :notices
      get :errata
      get :promotions
      get :systems
      get :system_groups
      get :subscriptions
    end
  end

  resources :systems do
    resources :events, :only => [:index, :show], :controller => "system_events" do
      collection do
        get :status
        get :more_events
        get :items
      end
    end
    resources :system_packages, :only => {} do
      collection do
        put :add
        post :remove
        post :update
        get :packages
        get :more_packages
        get :status
      end
    end
    resources :errata, :controller => "system_errata", :only => [:index, :update] do
      collection do
        get :items
        post :install
        get :status
      end
    end

    member do
      get :edit
      get :subscriptions
      post :update_subscriptions
      get :products
      get :more_products
      get :facts
      get :system_groups
      put :add_system_groups
      put :remove_system_groups
      get :custom_info
    end
    collection do
      get :auto_complete
      get :items
      get :env_items
      get :environments
      delete :bulk_destroy
      post :bulk_add_system_group
      post :bulk_remove_system_group
      post :bulk_content_install
      post :bulk_content_update
      post :bulk_content_remove
      post :bulk_errata_install
    end
  end
  resources :operations, :only => [:index]  do
  end

  resources :packages, :only => [:show] do
    member do
      get :changelog
      get :filelist
      get :dependencies
    end
    collection do
      get :auto_complete_library
      get :auto_complete_nvrea_library
      get :validate_name_library
    end
  end

  resources :errata, :only => [:show] do
    member do
      get :packages
      get :short_details
    end
  end

  resources :distributors do
    resources :events, :only => [:index, :show], :controller => "distributor_events" do
      collection do
        get :status
        get :more_events
        get :items
      end
    end

    member do
      get :edit
      get :subscriptions
      post :update_subscriptions
      get :products
      get :more_products
      get :download
    end
    collection do
      get :auto_complete
      get :items
      get :env_items
      get :environments
      delete :bulk_destroy
    end
  end

  resources :products, :only => [:new, :create, :edit,:update, :destroy] do
    collection do
       get :auto_complete
    end
  end

  resources :users do
    collection do
      get :auto_complete_search
      get :items
      post :enable_helptip
      post :disable_helptip
    end
    member do
      post :clear_helptips
      put :update_roles
      put :update_locale
      put :update_preference
      put :setup_default_org
      get :edit_environment
      put :update_environment
    end
  end

  resources :system_templates do
    collection do
      get :auto_complete_search
      get :items
      get :product_packages
      get :product_comps
      get :product_repos
    end
    member do
      get :promotion_details
      get :object
      get :download
      get :validate
      put :update_content
    end
  end

  resources :providers do
    collection do
      get :auto_complete_search
      put :refresh_products
    end

    resources :products do
      get :default_label, :on => :collection

      resources :repositories, :only => [:new, :create, :edit, :destroy] do
        get :default_label, :on => :collection
        member do
          put :update_gpg_key, :as => :update_repo_gpg_key
        end
      end
    end
    collection do
      get :items
      get :redhat_provider
      post :redhat_provider, :action => :update_redhat_provider
    end
    member do
      get :repo_discovery
      get :discovered_repos
      get :new_discovered_repos
      post :discover
      post :cancel_discovery
      get :products_repos
      get :manifest_progress
      get :schedule
    end
  end
  match '/providers/:id' => 'providers#update', :via => :put
  match '/providers/:id' => 'providers#update', :via => :post

  match '/repositories/:id/enable_repo' => 'repositories#enable_repo', :via => :put, :as => :enable_repo

  resources :repositories, :only => [:new, :create, :edit, :destroy] do
    get :auto_complete_library, :on => :collection

    resources :distributions, :only => [:show], :constraints => { :id => /[0-9a-zA-Z\-\+%_.]+/ } do
      member do
        get :filelist
      end
    end
  end

  resources :promotions, :only =>[] do
    collection do
      get :index, :action =>:show
    end
    member do
      get :show
      get :products
      get :packages
      get :errata
      get :system_templates
      get :repos
      get :distributions
      get :details
      get :content_views
    end

  end

  match '/organizations/:org_id/environments/:env_id/edit' => 'environments#update', :via => :put

  resources :organizations do
    collection do
      get :auto_complete_search
      get :items
      get :default_label
    end
    member do
      get :environments_partial
      get :events
      get :download_debug_certificate
    end
    resources :environments do
      get :default_label, :on => :collection
      member do
        get :system_templates
        get :products
        get :content_views
      end
      resources :content_view_versions, :only => [:show] do
        member do
          get :content
        end
      end
    end
  end
  match '/organizations/:id/edit' => 'organizations#update', :via => :put

  resources :changesets, :only => [:update, :index, :show, :create, :new, :edit, :destroy] do
    member do
      put :name
      get :dependencies
      post :apply
      get :status
      get :object
    end
    collection do
      get :auto_complete_search
      get :list
      get :items
    end
  end

  resources :environments

  match '/roles/show_permission' => 'roles#show_permission', :via=>:get

src/app/models/authorization/gpg_key.rb
#
# Copyright 2011 Red Hat, Inc.
#
# This software is licensed to you under the GNU General Public
# License as published by the Free Software Foundation; either version
# 2 of the License (GPLv2) or (at your option) any later version.
# There is NO WARRANTY for this software, express or implied,
# including the implied warranties of MERCHANTABILITY,
# NON-INFRINGEMENT, or FITNESS FOR A PARTICULAR PURPOSE. You should
# have received a copy of GPLv2 along with this software; if not, see
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.



module Authorization::GpgKey
  extend ActiveSupport::Concern


  module ClassMethods
    def readable(org)
       if org.readable? || org.gpg_keys_manageable? || ::Provider.any_readable?(org)
          where(:organization_id => org.id)
       else
         where("0 = 1")
       end
    end

    def manageable(org)
       if org.gpg_keys_manageable?
          where(:organization_id => org.id)
       else
         where("0 = 1")
       end
    end

    def createable?(organization)
      organization.gpg_keys_manageable?
    end

    def any_readable?(organization)
      organization.readable? || organization.gpg_keys_manageable? || ::Provider.any_readable?(organization)
    end
  end


  module InstanceMethods
    def readable?
       GpgKey.any_readable?(organization)
    end

    def manageable?
       organization.gpg_keys_manageable?
    end
  end

end

src/app/models/glue/elastic_search/gpg_key.rb
#
# Copyright 2011 Red Hat, Inc.
#
# This software is licensed to you under the GNU General Public
# License as published by the Free Software Foundation; either version
# 2 of the License (GPLv2) or (at your option) any later version.
# There is NO WARRANTY for this software, express or implied,
# including the implied warranties of MERCHANTABILITY,
# NON-INFRINGEMENT, or FITNESS FOR A PARTICULAR PURPOSE. You should
# have received a copy of GPLv2 along with this software; if not, see
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.


module Glue::ElasticSearch::GpgKey
  def self.included(base)
    base.send :include, Ext::IndexedModel

    base.class_eval do
      index_options :extended_json=>:extended_index_attrs,
                    :display_attrs=>[:name, :content]

      mapping do
        indexes :name, :type => 'string', :analyzer => :kt_name_analyzer
        indexes :name_sort, :type => 'string', :index => :not_analyzed
      end
    end
  end

  def extended_index_attrs
    {:name_sort=>name.downcase}
  end

end

src/app/controllers/api/gpg_keys_controller.rb
#
## Copyright 2011 Red Hat, Inc.
##
## This software is licensed to you under the GNU General Public
## License as published by the Free Software Foundation; either version
## 2 of the License (GPLv2) or (at your option) any later version.
## There is NO WARRANTY for this software, express or implied,
## including the implied warranties of MERCHANTABILITY,
## NON-INFRINGEMENT, or FITNESS FOR A PARTICULAR PURPOSE. You should
## have received a copy of GPLv2 along with this software; if not, see
## http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.


class Api::GpgKeysController < Api::ApiController

  skip_filter   :set_locale, :require_user, :thread_locals, :authorize, :only => [:content]

  before_filter :find_gpg_key, :only => [:content, :show, :update, :destroy]
  before_filter :find_organization, :only => [:index, :create]
  before_filter :authorize, :except => [:content]

  def rules
    read_test = lambda{@gpg_key.readable?}
    manage_test = lambda{@gpg_key.manageable?}
    create_test = lambda{GpgKey.createable?(@organization)}
    index_test = lambda{GpgKey.any_readable?(@organization)}
    {
      :index => index_test,
      :show => read_test,
      :create => create_test,
      :update => manage_test,
      :destroy => manage_test
    }
  end

  def param_rules
    {
        :create => {:gpg_key => [:name, :content]},
        :update => {:gpg_key => [:name, :content]}
    }
  end

  api :GET, "/organizations/:organization_id/gpg_keys", "List gpg keys"
  param :organization_id, :identifier, :desc => "organization identifier"
  param :name, :identifier, :desc => "identifier of the gpg key"
  def index
    gpg_keys = @organization.gpg_keys.where(params.slice(:name))
    render :json => gpg_keys, :only => [:id, :name]
  end

  api :GET, "/gpg_keys/:id", "Show a gpg key"
  param :id, :number, :desc => "gpg key numeric identifier"
  def show
    render :json => @gpg_key, :details => true
  end

  api :POST, "/organizations/:organization_id/gpg_keys", "Create a gpg key"
  param :organization_id, :identifier, :desc => "organization identifier"
  param :gpg_key, Hash do
    param :name, :identifier, :desc => "identifier of the gpg key"
    param :content, String, :desc => "public key block in DER encoding"
  end
  def create
    gpg_key = @organization.gpg_keys.create!(params[:gpg_key].slice(:name, :content))
    render :json => gpg_key
  end

  api :PUT, "/gpg_keys/:id", "Update a gpg key"
  see "gpg_keys#create"
  def update
    @gpg_key.update_attributes!(params[:gpg_key].slice(:name, :content))
    render :json => @gpg_key
  end

  api :DELETE, "/gpg_keys/:id", "Destroy a gpg key"
  param :id, :number, :desc => "gpg key numeric identifier"
  def destroy
    @gpg_key.destroy
    render :text => _("Deleted GPG key '%s'") % params[:id], :status => 204
  end

  api :GET, "/gpg_keys/:id/content"
  param :id, :number, :desc => "gpg key numeric identifier"
  desc <<-EOS
Returns the content of a repo gpg key, used directly by yum
We've amended REST best practices (e.g. not using the show action) as we don't want to
authenticate, authorize etc, trying to distinquse between a yum request and normal api request
might not always be 100% bullet proof, and its more important that yum can fetch the key.
EOS
  def content
    @gpg_key.content.present? ? render(:text => @gpg_key.content, :layout => false) : head(404)
  end

  private

  def find_gpg_key
    @gpg_key = GpgKey.find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    raise HttpErrors::NotFound, _("Couldn't find GPG key '%s'") % params[:id]
  end

end

src/app/helpers/gpg_keys_helper.rb
#
# Copyright 2011 Red Hat, Inc.
#
# This software is licensed to you under the GNU General Public
# License as published by the Free Software Foundation; either version
# 2 of the License (GPLv2) or (at your option) any later version.
# There is NO WARRANTY for this software, express or implied,
# including the implied warranties of MERCHANTABILITY,
# NON-INFRINGEMENT, or FITNESS FOR A PARTICULAR PURPOSE. You should
# have received a copy of GPLv2 along with this software; if not, see
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.

module GpgKeysHelper

end

src/app/views/gpg_keys/_edit.html.haml
= javascript :gpg_key_edit

= content_for :title do
  #{@gpg_key.name}

= content_for :remove_item do
  - if editable
    = link_to _("Remove GPG Key"), gpg_key_path(@gpg_key.id), :confirm => _('Are you sure?'), :method => :delete, :class=>"remove_item", :remote=>true

= content_for :navigation do
  = render_menu(1..2, gpg_keys_navigation)

= content_for :content do
  = help_tip_button('gpg_keys_edit-help')

  %input#panel_element_id{:name => @gpg_key.id, :type => "hidden", :value => "#{name}_#{@gpg_key.id}", "data-ajax_url"=>gpg_key_path(@gpg_key.id)}

  %div
    .full
      = help_tip(_("Edit GPG Key enables you to modify the selected GPG Key.  A new key can be copied and pasted in directly."), 'gpg_keys_edit-help') |

    .full
      %fieldset
        .grid_1.ra
          %label #{_("Name")}:
        .grid_8.la#gpg_key_name{'name' => 'gpg_key[name]', :class => editable_class(editable), 'data-url' => gpg_key_path(@gpg_key.id)} #{@gpg_key[:name]}
      = form_tag gpg_key_path(@gpg_key.id), :method => "post", "data-url" => gpg_key_path(@gpg_key.id), :id => "upload_gpg_key" do
        - if editable
          %fieldset
            .grid_1.ra
              %label #{_("Upload")}:
            .grid_3.la
              = file_field_tag 'gpg_key[content_upload]', :id => "gpg_key_content_upload_update", :tabindex => auto_tab_index
          %fieldset
            .grid_2.la.push_1
              %input.button{ "type" => "button", :id => :update_upload_gpg_key, :disabled => "disabled", :tabindex => auto_tab_index, "value" => _("Upload") }
            .grid_1.push_2.ra
              %input.button{ "type" => "button", :id => :clear_upload_gpg_key, :disabled => "disabled", :tabindex => auto_tab_index, "value" => _("Clear") }
      %fieldset
        .grid_1.ra
          %label #{_("Key")}:
        .grid_8.la
          .grid_8.la.multiline#gpg_key_content{'name' => 'gpg_key[content]', :class => ("editable edit_textarea" if editable), 'data-url' => gpg_key_path(@gpg_key.id)} #{@gpg_key[:content]}

= render :template => "layouts/tupane_layout"

src/app/views/gpg_keys/_new.html.haml
= content_for :title do
  #{_("New GPG Key")}

= content_for :content do
  .grid_10
    = kt_form_for GpgKey.new, :html => {:id => "upload_new_gpg_key"} do |form|

      = form.text_field :name, :label => _("Name"), :class => "grid_6"

      = form.file_field :content_upload, :id => "gpg_key_content_upload", :label => _("Upload"), :class => "grid_6"

      %fieldset
        .grid_2.la.push_2
          = submit_tag _("Upload"), :id => :upload_gpg_key, :tabindex => form.tabindex
        .grid_1.push_5
          = submit_tag _("Clear"), :id => :clear_upload_gpg_key, :disabled => true, :tabindex => form.tabindex, :type => 'button', :class => 'button'

      = form.field :or, :label => _("or")

    = kt_form_for GpgKey.new, :html => {:id => "new_gpg_key"}, :tabindex => 5 do |form|

      = form.text_area :content, :id=> "gpg_key_content", :size => "40x15", :label => _("Paste GPG Key"), :class => "grid_6"

      %fieldset
        .grid_2.la.push_2
          = submit_tag _("Save"), :id => :save_gpg_key, :tabindex => form.tabindex
        .grid_1.push_5
          = submit_tag _("Clear"), :id => :clear_gpg_key, :disabled => "disabled", :tabindex => form.tabindex, :type => 'button', :class => 'button'

= render :template => "layouts/tupane_layout"

src/app/views/gpg_keys/_products_repos.html.haml
= javascript :products_repos

= content_for :title do
  #{@gpg_key.name}

= content_for :remove_item do
  - if @gpg_key.manageable?
    = link_to _("Remove GPG Key"), {:action => "destroy", :controller => "gpg_keys"}, :method => :delete, :confirm => _('Are you sure you want to delete this GPG Key?'), :class => "remove_item", :remote=>true

= content_for :navigation do
  = render_menu(1..2, gpg_keys_navigation)

= content_for :content do
  #products_repos

    -if products.length == 0 and products_repos.length == 0
      #{_("This GPG Key is not currently assigned to any products or repositories.")}

    -if products.length > 0
      %h5
        #{_("GPG Key assigned at the Product Level for")}:
      %ul.bordered-table
        %div.block_head
          %div.column_head.column_1
            = _("Products")

        -products.each do |product|
          - cssclass = cycle("", "alt")
          %div{:class => cssclass}
            &nbsp;#{product.name}

      &nbsp;

    -if products_repos.length > 0
      %h5
        #{_("GPG Key assigned at the Repository Level for")}:
      %ul.bordered-table
        %div.block_head
          %div.column_head.column_1
            = _("Repositories")

        -products_repos.each do |element|
          - product = element[0]
          - repos = element[1]
          - cssclass = cycle("", "alt")
          %div.parent{:class => cssclass}
            %label #{_("Product")}:
            &nbsp;#{product}

          - repos.each do |repo|
            %div.child{:class => cssclass}
              %label #{_("Repository")}:
              &nbsp;#{repo.name}

= render :template => "layouts/tupane_layout"

src/app/views/gpg_keys/index.html.haml
.grid_16
  = help_tip_button
  = help_tip(_("GPG Keys may be stored by uploading a key directly or copying and pasting the key in upon creation. " + |
               "By visiting the Providers page and selecting either a product or repository, a GPG key that has been " + |
               "created here can be associated with the given entity.")) |

.grid_16#main
  = two_panel(@gpg_keys, @panel_options)

= javascript :gpg_key