src/config/routes.rb
Src::Application.routes.draw do

  apipie

  if Katello.config.use_foreman
    scope :module => 'foreman' do
      resources :subnets do
        collection do
          get :items
        end
      end

      resources :domains do
        collection do
          get :items
        end
      end

      resources :hardware_models do
        collection do
          get :items
        end
      end

      resources :architectures do
        collection do
          get :items
        end
      end

      resources :smart_proxies do
        collection do
          get :items
        end
      end
    end
  end

  resources :system_groups do
    collection do
      get :items
      get :auto_complete
      get :validate_name
    end
    member do
      post :copy
      get :systems
      post :add_systems
      post :remove_systems
      delete :destroy_systems
    end
    resources :events, :controller => "system_group_events", :only => [:index, :show] do
      collection do
        get :status
        get :more_items
        get :items
      end
    end
    resources :packages, :controller => "system_group_packages", :only => [:index] do
      collection do
        put :add
        put :remove
        put :update
        get :status
      end
    end
    resources :errata, :controller => "system_group_errata", :only => [:index] do
      collection do
        get :items
        post :install
        get :status
      end
    end
  end

  resources :content_search do
      collection do
        post :errata
        post :products
        post :packages
        post :packages_items
        post :errata_items
        post :repos
        post :views
        get :repo_packages
        get :repo_errata
        get :repo_compare_packages
        get :repo_compare_errata
      end
  end

  resources :content_view_definitions do
    collection do
      get :default_label
      get :items
    end
    member do
      post :clone
      get :views
      get :publish_setup
      post :publish
      get :status
      get :content
      post :update_content
      put :update_component_views
      get :filter
    end
    resources :content_view, :only => [], :controller => :content_view_definitions do
      member do
        post :refresh
      end
    end
  end

  resources :content_views do
    collection do
       get :auto_complete
    end
  end

  resources :activation_keys do
    collection do
      get :auto_complete_search
      get :items
      get :subscriptions
    end
    member do
      get :applied_subscriptions
      get :available_subscriptions
      post :remove_subscriptions
      post :add_subscriptions

      post :update

      get :system_groups
      get :systems
      put :add_system_groups
      put :remove_system_groups
    end
  end

  resources :gpg_keys do
    collection do
      get :auto_complete_search
      get :items
    end
    member do
      get :products_repos
      post :update
    end
  end

  resources :sync_plans, :only => [:index, :create, :new, :edit, :update, :show, :destroy, :auto_complete_search] do
    collection do
      get :auto_complete_search
      get :items
    end
  end

  get  "sync_schedules/index"
  post "sync_schedules/apply"

  get "sync_management/manage"
  get "sync_management/index"
  post "sync_management/sync"
  get  "sync_management/sync_status"
  get  "sync_management/product_status"
  resources :sync_management, :only => [:destroy]

  get "notices/note_count"
  get "notices/get_new"
  get "notices/auto_complete_search"
  match 'notices/:id/details' => 'notices#details', :via => :get, :as => 'notices_details'
  match 'notices' => 'notices#show', :via => :get
  match 'notices' => 'notices#destroy_all', :via => :delete

  resources :subscriptions do
    member do
      get :edit
      get :products
      get :consumers
    end
    collection do
      get :items
      post :upload
      post :delete_manifest
      get :history
      get :history_items
    end
  end

  resources :dashboard, :only => [:index] do
    collection do
      get :sync
      get :notices
      get :errata
      get :promotions
      get :systems
      get :system_groups
      get :subscriptions
    end
  end

  resources :systems do
    resources :events, :only => [:index, :show], :controller => "system_events" do
      collection do
        get :status
        get :more_events
        get :items
      end
    end
    resources :system_packages, :only => {} do
      collection do
        put :add
        post :remove
        post :update
        get :packages
        get :more_packages
        get :status
      end
    end
    resources :errata, :controller => "system_errata", :only => [:index, :update] do
      collection do
        get :items
        post :install
        get :status
      end
    end

    member do
      get :edit
      get :subscriptions
      post :update_subscriptions
      get :products
      get :more_products
      get :facts
      get :system_groups
      put :add_system_groups
      put :remove_system_groups
      get :custom_info
    end
    collection do
      get :auto_complete
      get :items
      get :env_items
      get :environments
      delete :bulk_destroy
      post :bulk_add_system_group
      post :bulk_remove_system_group
      post :bulk_content_install
      post :bulk_content_update
      post :bulk_content_remove
      post :bulk_errata_install
    end
  end
  resources :operations, :only => [:index]  do
  end

  resources :packages, :only => [:show] do
    member do
      get :changelog
      get :filelist
      get :dependencies
    end
    collection do
      get :auto_complete_library
      get :auto_complete_nvrea_library
      get :validate_name_library
    end
  end

  resources :errata, :only => [:show] do
    member do
      get :packages
      get :short_details
    end
  end

  resources :distributors do
    resources :events, :only => [:index, :show], :controller => "distributor_events" do
      collection do
        get :status
        get :more_events
        get :items
      end
    end

    member do
      get :edit
      get :subscriptions
      post :update_subscriptions
      get :products
      get :more_products
      get :download
    end
    collection do
      get :auto_complete
      get :items
      get :env_items
      get :environments
      delete :bulk_destroy
    end
  end

  resources :products, :only => [:new, :create, :edit,:update, :destroy] do
    collection do
       get :auto_complete
    end
  end

  resources :users do
    collection do
      get :auto_complete_search
      get :items
      post :enable_helptip
      post :disable_helptip
    end
    member do
      post :clear_helptips
      put :update_roles
      put :update_locale
      put :update_preference
      put :setup_default_org
      get :edit_environment
      put :update_environment
    end
  end

  resources :system_templates do
    collection do
      get :auto_complete_search
      get :items
      get :product_packages
      get :product_comps
      get :product_repos
    end
    member do
      get :promotion_details
      get :object
      get :download
      get :validate
      put :update_content
    end
  end

  resources :providers do
    collection do
      get :auto_complete_search
      put :refresh_products
    end

    resources :products do
      get :default_label, :on => :collection

      resources :repositories, :only => [:new, :create, :edit, :destroy] do
        get :default_label, :on => :collection
        member do
          put :update_gpg_key, :as => :update_repo_gpg_key
        end
      end
    end
    collection do
      get :items
      get :redhat_provider
      post :redhat_provider, :action => :update_redhat_provider
    end
    member do
      get :repo_discovery
      get :discovered_repos
      get :new_discovered_repos
      post :discover
      post :cancel_discovery
      get :products_repos
      get :manifest_progress
      get :schedule
    end
  end
  match '/providers/:id' => 'providers#update', :via => :put
  match '/providers/:id' => 'providers#update', :via => :post

  match '/repositories/:id/enable_repo' => 'repositories#enable_repo', :via => :put, :as => :enable_repo

  resources :repositories, :only => [:new, :create, :edit, :destroy] do
    get :auto_complete_library, :on => :collection

    resources :distributions, :only => [:show], :constraints => { :id => /[0-9a-zA-Z\-\+%_.]+/ } do
      member do
        get :filelist
      end
    end
  end

  resources :promotions, :only =>[] do
    collection do
      get :index, :action =>:show
    end
    member do
      get :show
      get :products
      get :packages
      get :errata
      get :system_templates
      get :repos
      get :distributions
      get :details
      get :content_views
    end

  end

  match '/organizations/:org_id/environments/:env_id/edit' => 'environments#update', :via => :put

  resources :organizations do
    collection do
      get :auto_complete_search
      get :items
      get :default_label
    end
    member do
      get :environments_partial
      get :events
      get :download_debug_certificate
    end
    resources :environments do
      get :default_label, :on => :collection
      member do
        get :system_templates
        get :products
        get :content_views
      end
      resources :content_view_versions, :only => [:show] do
        member do
          get :content
        end
      end
    end
  end
  match '/organizations/:id/edit' => 'organizations#update', :via => :put

  resources :changesets, :only => [:update, :index, :show, :create, :new, :edit, :destroy] do
    member do
      put :name
      get :dependencies
      post :apply
      get :status
      get :object
    end
    collection do
      get :auto_complete_search
      get :list
      get :items
    end
  end

  resources :environments

  match '/roles/show_permission' => 'roles#show_permission', :via=>:get

src/app/models/authorization/system.rb
#
# Copyright 2011 Red Hat, Inc.
#
# This software is licensed to you under the GNU General Public
# License as published by the Free Software Foundation; either version
# 2 of the License (GPLv2) or (at your option) any later version.
# There is NO WARRANTY for this software, express or implied,
# including the implied warranties of MERCHANTABILITY,
# NON-INFRINGEMENT, or FITNESS FOR A PARTICULAR PURPOSE. You should
# have received a copy of GPLv2 along with this software; if not, see
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.



module Authorization::System
  extend ActiveSupport::Concern


  module ClassMethods
    # returns list of virtual permission tags for the current user
    def list_tags
      select('id,name').all.collect { |m| VirtualTag.new(m.id, m.name) }
    end

    def readable(org)
      raise "scope requires an organization" if org.nil?
      if org.systems_readable?
         where(:environment_id => org.environment_ids) #list all systems in an org
      else #just list for environments the user can access
        where_clause = "systems.environment_id in (#{::KTEnvironment.systems_readable(org).select(:id).to_sql})"
        where_clause += " or "
        where_clause += "system_system_groups.system_group_id in (#{::SystemGroup.systems_readable(org).select(:id).to_sql})"
        joins("left outer join system_system_groups on systems.id =
                                    system_system_groups.system_id").where(where_clause)
      end
    end

    def any_readable?(org)
      org.systems_readable? ||
        ::KTEnvironment.systems_readable(org).count > 0 ||
        ::SystemGroup.systems_readable(org).count > 0
     end

    #TODO these two functions are somewhat poorly written and need to be redone
    def any_deletable?(env, org)
      if env
        env.systems_deletable? || org.system_groups.any?{|g| g.systems_deletable?}
      else
        org.systems_deletable? || org.system_groups.any?{|g| g.systems_deletable?}
      end
    end

    def registerable?(env, org)
      if env
        env.systems_registerable?
      else
        org.systems_registerable?
      end
    end
  end

  module InstanceMethods
    def readable?
      sg_readable = false
      if Katello.config.katello?
        sg_readable = !::SystemGroup.systems_readable(self.organization).where(:id=>self.system_group_ids).empty?
      end
      environment.systems_readable? || sg_readable
    end

    def editable?
      sg_editable = false
      if Katello.config.katello?
        sg_editable = !::SystemGroup.systems_editable(self.organization).where(:id=>self.system_group_ids).empty?
      end
      environment.systems_editable? || sg_editable
    end

    def deletable?
      sg_deletable = false
      if Katello.config.katello?
        sg_deletable = !::SystemGroup.systems_deletable(self.organization).where(:id=>self.system_group_ids).empty?
      end
      environment.systems_deletable? || sg_deletable
    end
  end

end

src/app/helpers/systems_helper.rb
#
# Copyright 2011 Red Hat, Inc.
#
# This software is licensed to you under the GNU General Public
# License as published by the Free Software Foundation; either version
# 2 of the License (GPLv2) or (at your option) any later version.
# There is NO WARRANTY for this software, express or implied,
# including the implied warranties of MERCHANTABILITY,
# NON-INFRINGEMENT, or FITNESS FOR A PARTICULAR PURPOSE. You should
# have received a copy of GPLv2 along with this software; if not, see
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.

module SystemsHelper

  def render_rows(options)
    render :partial=>"systems/list_systems",
            :locals=>{:accessor=>options[:accessor], :columns=>options[:columns], :collection=>options[:collection], :name=>options[:name]}
  end

  def get_checkin(system)
    if system.checkinTime
      return  format_time(system.checkinTime)
    end
    _("Never checked in")
  end

  def get_registered(system)
    if system.createdTime
      return  format_time(system.createdTime)
    end
    _("Unknown registration date")
  end

  def get_uptime
    return '0 days'
  end

  def convert_time(item)
    format_time(Time.parse(item))
  end

  def architecture_select
    select(:arch, "arch_id", System.architectures.invert,
             {:prompt => _('Select Architecture'), :id=>"arch_field"}, {:tabindex => 3})
  end

  def content_view_select(org)
    views = ContentView.readable(org).non_default
    choices = views.map {|v| [v.name, v.id]}
    select(:system, "content_view_id", choices,
             {:prompt => _('Select Content View'), :id=>"content_view_field"},
             {:tabindex => 2})
  end

  def system_content_view_opts
    keys = {}
    ContentView.readable(current_organization).non_default.each do |view|
      keys[view.id] = view.name
    end
    keys[""] = ""
    keys["selected"] = @system.content_view_id || ""

    keys.to_json
  end

  def virtual_buttons
    raw [radio_button("system_type","virtualized", "physical", :checked=>true, :tabindex => 5 ),
    content_tag(:label, _("Physical"), :for => 'system_type_virtualized_physical'),
    radio_button("system_type","virtualized", "virtual", :tabindex => 6 ),
    content_tag(:label, _("Virtual"), :for => 'system_type_virtualized_virtual')].join(' ')
  end

  def errata_type_class errata
    case errata.e_type
      when  Errata::SECURITY
        return "security_icon"
      when  Errata::ENHANCEMENT
        return "enhancement_icon"
      when  Errata::BUGZILLA
        return "bugzilla_icon"
    end
  end

  def system_type system

    return _("Guest") if system.guest == 'true'

    case system
      when Hypervisor
        _("Hypervisor")
      else
        _("Host")
    end
  end

  def system_releasevers_edit system, releases
    vers = {}
    releases.each { |ver|
      vers[ver] = ver
    }

    vers[""] = ""
    vers["selected"] = system[:releaseVer]

    return vers.to_json
  end

  def system_servicelevel system
    _("Auto-attach %{val}, %{sla}") %
      {:val => system.autoheal ? _("On") : _("Off"),
       :sla => ( system.serviceLevel == '' ? _("No Service Level Preference") : (_("Service Level %s") % system.serviceLevel))}
  end

  def system_servicelevel_edit system
    levels = {}
    system.organization.service_levels.each { |level|
      levels["1#{level}"] = _("Auto-attach On, Service Level %s") % level
      levels["0#{level}"] = _("Auto-attach Off, Service Level %s") % level
    }

    levels['1'] = _("Auto-attach On, No Service Level Preference")
    levels['0'] = _("Auto-attach Off, No Service Level Preference")

    levels["selected"] = system_servicelevel(system)

    return levels.to_json
  end

  def system_environment_name system
    system.environment.name
  end

end

src/app/views/systems/_edit.html.haml
= javascript do
  :plain
    KT.available_environments = $.parseJSON('#{escape_javascript(environments.to_json)}');
    localize({
        "systemReleaseVerDefault": '#{escape_javascript(_("System Default"))}'
    });

= javascript :edit_helpers, :system_edit
= render :partial => "system_tupane_header_nav"

= content_for :content do
  #system
    %input#panel_element_id{:name => @system.id, :type => "hidden", :value => "#{name}_#{system.id.to_s}", "data-ajax_url"=>url_for(:action=> 'update')}
    .grid_8
      %h5 #{_("System Info")}
    .grid_8#system_info
      %fieldset
        .grid_2.ra.fieldset
          = label :id, :id, _("ID")
        .grid_5.la #{system.id}
      %fieldset
        .grid_2.ra.fieldset
          = label :uuid, :uuid, _("UUID")
        .grid_5.la #{system.uuid}
    .clear
    .grid_8
      %h5 #{_("Networking")}
    .grid_8#system_info
      %fieldset
        .grid_2.ra.fieldset
          = label :hostname, :hostname, _("Hostname")
        .grid_5.la #{system.hostname}
      %fieldset
        .grid_2.ra.fieldset
          = label :interfaces, :interfaces, _("Interfaces")
        .grid_5
          %table#interface_table
            - system.interfaces.each do |interface|
              %tr
                %td.interface_name
                  = interface[:name]
                %td.interface_addr
                  = interface[:addr]
    .clear
    .grid_8
      %h5 #{_("System Properties")}
    .grid_8#system_properties
      %fieldset
        .grid_2.ra.fieldset
          = label :system, :name, _("Name")
        .grid_5.la#system_name{'name' => 'system[name]', :class=>("editable edit_panel_element" if editable), 'data-url'=>system_path(system.id)} #{system[:name]}
      %fieldset
        .grid_2.ra.fieldset
          = label :system, :description, _("Description")
        .grid_5.la#system_description{'name' => 'system[description]', :class=>("editable edit_textarea" if editable), 'data-url'=>system_path(system.id)} #{system[:description]}
      %fieldset
        .grid_2.ra.fieldset
          = label :os, :os, _("OS")
        .grid_5.la #{system.distribution_name}
      %fieldset
        .grid_2.ra.fieldset
          = label :release, :release, _("Release")
        .grid_5.la #{system.kernel}
      %fieldset
        .grid_2.ra.fieldset
          - help_message = _("Setting the release version limits content to this version only, preventing newer packages from being available for installation.")
          %span.tipsify.details_icon-grey{:title => help_message}
          = label :releaseVer, :releaseVer, _("Release Version")
        - if !releases_error.nil?
          .grid_5.la{'name' => 'system[releaseVer]', 'class' => ("editable edit_select_system_releasever_message error_message" if editable), 'data-url'=>system_path(system.id), 'data-message'=>releases_error}
            = system.release == "" ? _("System Default") : system.release
        - elsif releases == []
          - if Katello.config.katello?
            - none_message = ("No alternate release version choices are available. These choices are based upon the repositories that have been enabled and promoted to this system's environment.")
          - else
            - none_message = _("No alternate release version choices are available. These choices are based upon the Red Hat manifest imported and the content available in the CDN.")
          .grid_5.la{'name' => 'system[releaseVer]', 'class' => ("editable edit_select_system_releasever_message" if editable), 'data-url'=>system_path(system.id), 'data-message'=>none_message}
            = system.release == "" ? _("System Default") : system.release
        - else
          .grid_5.la{'name' => 'system[releaseVer]', 'class' => ("editable edit_select_system_releasever" if editable), 'data-url' => system_path(system.id), 'data-options' => system_releasevers_edit(system, releases)}
            = system.release
      %fieldset
        .grid_2.ra.fieldset
          = label :arch, :arch, _("Arch")
        .grid_5.la #{System.architectures[system.arch]}
      %fieldset
        .grid_2.ra.fieldset
          = label :memory, :memory, _("RAM (MB)")
        .grid_5.la #{system.memory}
      %fieldset
        .grid_2.ra.fieldset
          = label :sockets, :sockets, _("Sockets")
        .grid_5.la #{system.sockets}
      %fieldset
        .grid_2.ra.fieldset
          = label :location, :location, _("Location")
        .grid_5.la#system_location{'name' => 'system[location]', :class=>("editable edit_textfield" if editable), 'data-url'=>system_path(system.id)} #{system[:location]}
      %fieldset
        .grid_2.ra.fieldset
          = label :arch, :arch, _("Environment")
        .grid_5.la#environment_path_selector{'name'=> 'system[environment_id]', :class=>("editable" if editable), 'data-url'=>system_path(system.id)}
          %span #{system_environment_name system}
      - if Katello.config.katello?
        %fieldset
          .grid_2.ra.fieldset
            = label :content_view, :content_view, _("Content View")
          .grid_5.la#system_content_view{'name' => 'system[content_view_id]', :class=>("editable edit_select" if editable), 'data-url'=>system_path(system.id), 'data-options' => system_content_view_opts} #{system.content_view}

    .clear
    .grid_8
      %h5 #{_("System Events")}
    .grid_8#system_events
      %fieldset
        .grid_2.ra.fieldset
          = label :checked_in, :checked_in, _("Checked In")
        .grid_5.la
          = get_checkin(system)
      %fieldset
        .grid_2.ra.fieldset
          = label :registered_date, :registered_date, _("Registered")
        .grid_5.la
          = convert_time(system.created)
      %fieldset
        .grid_2.ra.fieldset
          = label :last_booted, :last_booted, _("Last Booted")
        .grid_5.la #{_("None")}
      %fieldset
        .grid_2.ra.fieldset
          = label :host_guest, :activation_key, _("Activation Key")
        - if @system.activation_keys.blank?
          .grid_5.la= _("None")
        - else
          .grid_5
            - @system.activation_keys.each do |key|
              %table#interface_table
                %tr
                  %td
                    - if ActivationKey.readable? key.organization
                      = link_to key.name, activation_keys_path(:anchor => "panel=activation_key_#{key.id}")
                    - else
                      = key[:name]
    .clear
    .grid_8
      %h5 #{_("Host & Guest Info")}
    .grid_8#system_host_guest

      %fieldset
        .grid_2.ra.fieldset
          = label :host_guest, :host_type, _("System Type")
        .grid_5.la
          = system_type system

      %fieldset
        - if system.guest == 'true'
          .grid_2.ra.fieldset
            = label :host_guest, :host, _("Host")
          .grid_5.la
            = system.host ? system.host.attributes['name'] : _("Unknown")
        -else
          .grid_2.ra.fieldset
            = label :host_guest, :guest, _("Guests")
          - if system.guests.length < 1
            .grid_5.la
              = _("None")
          - else
            .grid_5.la
              %ul
              - system.guests.each do |guest|
                %li{:style=>'list-style: none;'}
                  = guest.attributes['name']

= render :template => "layouts/tupane_layout"

src/app/views/systems/_edit_custom_info.html.haml
= javascript :edit_helpers, :system_edit
= render :partial => "systems/system_tupane_header_nav"

= render :partial => "custom_info/edit",
         :locals => { :informable => @system,
                      :informable_type => "system",
                      :informable_id => @system.id }

src/app/views/systems/_list_system.html.haml
.block.tall{:id => "#{name}_#{item.send(accessor)}", "data-ajax_url" => "#{url_for(:controller=>controller.controller_name)}/#{item.send(accessor)}", "data-ajax_panelpage" => @panel_options[:initial_action]}
  = render :partial=>"systems/list_system_show", :locals=>{:item => item}

src/app/views/systems/_more_products.html.haml
-products.each do |p|
  %tr
    %td{:class=>'product'}
      .status_icon{:class => "#{@system.product_compliance_color p['productId']}"}
      #{p['productName']}

src/app/views/systems/_subs.html.haml
= include_javascripts :treetable

%div
  %h5
    = form_tag system_path(@system), :id=>"autoheal_form", :method=>"put", :remote=>true do
      #{_("System Current Subscription(s)")}
  = form_tag update_subscriptions_system_path, :id=>"unsubscribe", :method=>"post", :remote=>true do
    = hidden_field_tag "subscribe_action", "unsubscribe"
    .tree
      %table#unsubscribeTable
        %thead
          %tr
            %th
            %th #{_("Subscription")}
            %th #{_("SLA")}
            %th #{_("Contract")}
            %th #{_("Quantity")}
            %th #{_("Start")}
            %th #{_("End")}
        %tbody
          - if consumed_entitlements.length > 0
            - for entitlement in consumed_entitlements
              - cycle_class = cycle("", "alt")
              %tr{:id => "#{entitlement.entitlementId}", :class => cycle_class}
                %td{:style => "padding-top:9px;"}
                %td{:style => "padding-top:9px;", :colspan => '6'}
                  - if editable
                    %span.fl= check_box_tag "subscription[#{entitlement.entitlementId}]", value="#{entitlement.entitlementId}", false
                  &nbsp;
                  = subscriptions_pool_link_helper(entitlement.poolName, entitlement.poolId, entitlement.provider_id, current_organization)
              %tr{:id => "#{entitlement.entitlementId}-row2", :class => cycle_class}
                %td{:style => "padding-top:9px;"}
                %td{:style => "padding-top:9px;"}
                %td{:style => "padding-top:9px;"} #{entitlement.sla}
                %td{:style => "padding-top:9px;"} #{entitlement.contractNumber}
                %td{:style => "padding-top:9px;"}
                  = entitlement.quantity < 0 ? 1 : entitlement.quantity
                %td{:style => "padding-top:9px;"} #{format_time entitlement.startDate}
                %td{:style => "padding-top:9px;"} #{format_time entitlement.endDate}
              - entitlement.providedProducts.each do |product|
                %tr{:class => "child-of-#{entitlement.entitlementId} " + cycle_class}
                  %td{:colspan=>7}
                    %ul
                      %li
                        = _("Product Name: ")
                        = product.name
          - else
            %tr
              %td{:colspan=>7} #{_("There are currently no subscriptions attached to the system")}
      - if editable && consumed_entitlements.length > 0
        .actions
          %a{:class=>'dialogbutton button disabled', :id=>"fake_unsub_submit"} #{_('Remove')}
          = submit_tag _('Remove'), :class => 'update_subscriptions submit dialogbutton', :id=>"unsub_submit"
%br
%div
  %h5
    #{_("Available Subscriptions")}
  = form_tag update_preference_user_path(current_user), :id=>"matchsystem_form", :method=>"put", :remote=>false do
    = select_tag 'subscription_filters', subscription_filters.html_safe, :prompt => _("Filters"), :multiple => true, "data-placeholder" => _("Subscription Filter Options"), :disabled => true
  = form_tag update_subscriptions_system_path, :id=>"subscribe", :method=>"post", :remote=>true do
    = hidden_field_tag "subscribe_action", "subscribe"
    %div.hidden#available_spinner
      %table
        %thead
          %tr
            %th
            %th #{_("Subscription")}
            %th #{_("SLA")}
            %th #{_("Limits")}
            %th #{_("Quantity")}
            %th #{_("Start")}
            %th #{_("End")}
        %tbody
          %tr
            %td{:colspan=>7}
              .spinner{:style=>"margin-top:20px;"}
    %div#available_section
      .tree
        %table#subscribeTable
          %thead
            %tr
              %th
              %th #{_("Subscription")}
              %th #{_("SLA")}
              %th #{_("Limits")}
              %th #{_("Quantity")}
              %th #{_("Start")}
              %th #{_("End")}
          %tbody
            - if avail_subs.length > 0
              - reset_cycle()  # Always start table with a light colored line
              - for sub in avail_subs
                - cycle_class = cycle("", "alt")
                %tr{:id => "#{sub.cp_id}", :class => cycle_class}
                  %td{:style => "padding-top:9px;"}
                  %td{:style => "padding-top:9px;", :colspan => '6'}
                    - if editable
                      %span.fl= check_box_tag "subscription[#{sub.cp_id}]", false
                    &nbsp;
                    = subscriptions_pool_link_helper(sub.product_name, sub.cp_id, sub.provider_id, current_organization)
                %tr{:id => "#{sub.cp_id}-row2", :class => cycle_class}
                  %td{:style => "padding-top:9px;"}
                  %td{:style => "padding-top:9px;"}
                  %td{:style => "padding-top:9px;"} #{sub.support_level}
                  %td{:style => "padding-top:9px;"}
                    = _("Sockets: %s") % sub.sockets
                    = _(", RAM: %s") % sub.ram if sub.ram != 0
                  - if sub.multi_entitlement
                    %td
                      = text_field_tag "spinner[#{sub.cp_id}]", nil, :min => 0, :max => (sub.quantity-sub.consumed), :step=>1, :value=>0, :class=>"ui-spinner"
                      %span{:style => "padding-top:9px;"}
                        = "of #{sub.quantity - sub.consumed}"
                  - else
                    %td{:style => "padding-top:9px;"}
                      - if sub.quantity < 0
                        = _("Unlimited")
                      -else
                        %div{:id=>"spinner_label_#{sub.cp_id}", :class=>"ui-nonspinner-label"} 0 of #{sub.quantity - sub.consumed}
                      = hidden_field_tag "spinner[#{sub.cp_id}]", 0, :class => "ui-nonspinner"
                  %td{:style => "padding-top:9px;"} #{format_time sub.start_date}
                  %td{:style => "padding-top:9px;"} #{format_time sub.end_date}
                - sub.provided_products.each do |product|
                  %tr{:class => "child-of-#{sub.cp_id} " + cycle_class}
                    %td{:colspan=>7}
                      %ul
                        %li
                          = _("Product Name: ")
                          = product['productName']
            - else
              %tr
                %td{:colspan=>7} #{_("There are no more subscriptions available.")}
        - if editable && avail_subs.length > 0
          .actions
            = submit_tag _('Attach'), :class => 'submit dialogbutton', :id=>"sub_submit"
            %a{:class=>'dialogbutton button disabled', :id=>"fake_sub_submit"} #{_('Attach')}

src/app/views/systems/_subs_update.js.haml
!= "KT.panel.panelAjax('', '#{escape_javascript(subscriptions_system_path)}' ,$('#panel'));"